- name: install fail2ban from source
  command: python setup.py install --install-script /usr/local/bin
  args:
    chdir: /opt/fail2ban/
  become: yes
  listen: source_install_fail2ban
  notify: restart fail2ban

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
  become: yes

- name: reload fail2ban
  service:
    name: fail2ban
    state: reloaded
  become: yes
