- block:

  - name: ensure sudo is installed
    package:
      name: sudo
      state: present

  - name: ensure wheel group exists
    group:
      name: wheel
      system: yes

  - name: ensure sudoers file is up to date
    template:
      src: sudoers
      dest: /etc/sudoers
      backup: yes
      validate: '/usr/sbin/visudo -cf %s'
      owner: root
      group: root
      mode: 644

  become: yes
  tags:
  - sudo
  - credentials
