- name: ensure nftables is installed
  package:
    name: nftables
  become: yes

- name: ensure iptables is not installed
  package:
    name: iptables
    state: absent
  become: yes

- name: ensure /etc/nftables.d/ exists
  file:
    state: directory
    dest: /etc/nftables.d
  become: yes
  notify: reload nftables

- name: ensure nftconfig gets loaded
  service:
    name: nftables
    enabled: yes
  become: yes

- name: ensure the default configs in /etc/nftables.d/ are up to date
  template:
    src: "{{ item }}"
    dest: /etc/nftables.d/{{ item }}
  become: yes
  notify: reload nftables
  loop:
  - 00-flush_ruleset.nft
  - 30-global.nft
