- name: aquire files in /etc/nftables.d/
  shell: find '/etc/nftables.d/' -type f -iname '[^.]*.nft' | sort
  register: nftablesd_files
  changed_when: no
  become: yes

- name: ensure /etc/nftables.conf is up to date
  template:
    src: nftables.conf
    dest: /etc/nftables.conf
    backup: yes
  become: yes

- name: do the reload of nftables
  service:
    name: nftables
    state: reloaded
  become: yes
